#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cdparanoia
Version  : 10.2
Release  : 2
URL      : http://downloads.xiph.org/releases/cdparanoia/cdparanoia-III-10.2.src.tgz
Source0  : http://downloads.xiph.org/releases/cdparanoia/cdparanoia-III-10.2.src.tgz
Summary  : A Compact Disc Digital Audio (CDDA) extraction tool (or ripper).
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: cdparanoia-bin = %{version}-%{release}
Requires: cdparanoia-lib = %{version}-%{release}
Requires: cdparanoia-license = %{version}-%{release}
Requires: cdparanoia-man = %{version}-%{release}

%description
[September 11, 2008]
Monty <monty@xiph.org>
This CDDA reader distribution ('cdparanoia') reads audio from the
CDROM directly as data, with no analog step between, and writes the
data to a file or pipe as .wav, .aifc or as raw 16 bit linear PCM.

%package bin
Summary: bin components for the cdparanoia package.
Group: Binaries
Requires: cdparanoia-license = %{version}-%{release}

%description bin
bin components for the cdparanoia package.


%package dev
Summary: dev components for the cdparanoia package.
Group: Development
Requires: cdparanoia-lib = %{version}-%{release}
Requires: cdparanoia-bin = %{version}-%{release}
Provides: cdparanoia-devel = %{version}-%{release}
Requires: cdparanoia = %{version}-%{release}

%description dev
dev components for the cdparanoia package.


%package lib
Summary: lib components for the cdparanoia package.
Group: Libraries
Requires: cdparanoia-license = %{version}-%{release}

%description lib
lib components for the cdparanoia package.


%package license
Summary: license components for the cdparanoia package.
Group: Default

%description license
license components for the cdparanoia package.


%package man
Summary: man components for the cdparanoia package.
Group: Default

%description man
man components for the cdparanoia package.


%prep
%setup -q -n cdparanoia-III-10.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565112926
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static ac_objext=o
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
export SOURCE_DATE_EPOCH=1565112926
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cdparanoia
cp COPYING-GPL %{buildroot}/usr/share/package-licenses/cdparanoia/COPYING-GPL
cp COPYING-LGPL %{buildroot}/usr/share/package-licenses/cdparanoia/COPYING-LGPL
cp debian/copyright %{buildroot}/usr/share/package-licenses/cdparanoia/debian_copyright
%make_install BINDIR=%{buildroot}%{_bindir} MANDIR=%{buildroot}%{_mandir} LIBDIR=%{buildroot}%{_libdir} INCLUDEDIR==%{buildroot}%{_includedir}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cdparanoia

%files dev
%defattr(-,root,root,-)
/usr/lib64/libcdda_interface.so
/usr/lib64/libcdda_paranoia.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcdda_interface.so.0
/usr/lib64/libcdda_interface.so.0.10.2
/usr/lib64/libcdda_paranoia.so.0
/usr/lib64/libcdda_paranoia.so.0.10.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cdparanoia/COPYING-GPL
/usr/share/package-licenses/cdparanoia/COPYING-LGPL
/usr/share/package-licenses/cdparanoia/debian_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cdparanoia.1
